language: php
php:
    - '7.0'
    - nightly
before_script:
    - composer install --dev --no-interaction
    - composer dump-autoload
script:
    - mkdir -p build/logs
    - phpdbg -qrr ./vendor/bin/phpunit
after_script:
    - php vendor/bin/coveralls -v
