language: php
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly
matrix:
    allow_failures:
        - php: nightly
before_script:
    - composer install --dev --no-interaction
    - composer dump-autoload
script:
    - mkdir -p build/logs
    - phpdbg -qrr ./vendor/bin/phpunit
after_script:
    - php vendor/bin/coveralls -v
