site_name: Vector
site_description: 'Functional primitives for PHP'
site_author: 'Joseph Walker'
site_url: 'https://packagist.org/packages/vector/core'
repo_name: GitHub
repo_url: 'https://github.com/joseph-walker/vector'
copyright: 'Copyright (c) 2016 Joseph Walker'
theme: readthedocs
markdown_extensions:
    - admonition
extra_css:
    - extra.css
pages:
    -
        Introduction: index.md
    -
        'User Guide':
            -
                'Functional Basics': user-guide/basics.md
            -
                'Vector Modules': user-guide/module.md
    -
        Vector:
            -
                Lib:
                    -
                        ArrayList: auto-generate/Vector/Lib/ArrayList.md
                    -
                        Lambda: auto-generate/Vector/Lib/Lambda.md
                    -
                        Logic: auto-generate/Vector/Lib/Logic.md
                    -
                        Math: auto-generate/Vector/Lib/Math.md
                    -
                        Object: auto-generate/Vector/Lib/Object.md
                    -
                        Strings: auto-generate/Vector/Lib/Strings.md
            -
                Control:
                    -
                        Applicative: auto-generate/Vector/Control/Applicative.md
                    -
                        Functor: auto-generate/Vector/Control/Functor.md
                    -
                        Lens: auto-generate/Vector/Control/Lens.md
                    -
                        Monad: auto-generate/Vector/Control/Monad.md
