site_name: Vector
pages:
- Introduction: index.md
- User Guide:
    - Functional Basics: 'user-guide/basics.md'
    - The Function Capsule: 'user-guide/capsule.md'
- API Reference:
    - Data:
        - Maybe: 'api-reference/maybe.md'
        - Either: 'api-reference/either.md'
    - Lib:
        - Math: 'api-reference/math.md'
theme: readthedocs
