site_name: Vector
site_description: 'Functional primitives for PHP'
site_author: 'Joseph Walker'
site_url: 'https://packagist.org/packages/vector/core'
repo_name: GitHub
repo_url: 'https://github.com/joseph-walker/vector'
copyright: 'Copyright (c) 2016 Joseph Walker'
theme: material
markdown_extensions:
    - admonition
extra_css:
    - extra.css
pages:
    -
        Introduction: index.md
    -
        'User Guide':
            -
                'Functional Basics': user-guide/basics.md
            -
                'The Function Capsule': user-guide/capsule.md
    -
        'API Reference':
            -
                Data:
                    -
                        Maybe: api-reference/maybe.md
                    -
                        Either: api-reference/either.md

